services:
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=mollusc
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    ports:
      - '5432:5432'
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  spring-postgres: